### PR TITLE
Loosen initial blueprint parsing to support sphere and swarm blueprints

### PR DESCRIPTION
**Pull request by mattr-**
This PR removes some of the hardcoding in the gem around the string `BLUEPRINT:` in order to provide incredibly rudimentary support for handling sphere and swarm blueprints. Sphere blueprints and factory blueprints share a few common traits:

 - The type of a blueprint is at the very beginning of the blueprint string with a colon as a separator. `BLUEPRINT` for factories, `DYBP` for sphere and swarm blueprints.
 - The header section of a blueprint exists between the colon and the first double-quote of the blueprint string.
 - The encoded section of the blueprint exists between the two double quotes in the blueprint.
 - The final bit after the encoded section of the blueprint is the weird DSP specific MD5 hash variant.

This is not complete sphere/swarm blueprint support for the gem as I haven't yet figured out how the encoded section of sphere or swarm blueprints are structured.

### CODE REVIEW

**Review by LRFalk01 — COMMENTED** [review]
You sure about supporting any string as a starts with? Seems like we should look for either BLUEPRINT: or DYBP:

Thoughts?

**Comment by LRFalk01** [comment]
Dyson blueprint header:
```
public string headerStr => "DYBP:0," + this.time.Ticks.ToString() + "," + this.gameVersion + "," + ((int) this.type).ToString() + "," + this.latLimit.ToString() + "\"";
```

Building blueprint header:
```
public string headerStr => "BLUEPRINT:0," + ((int) this.layout).ToString() + "," + this.icon0.ToString() + "," + this.icon1.ToString() + "," + this.icon2.ToString() + "," + this.icon3.ToString() + "," + this.icon4.ToString() + ",0," + this.time.Ticks.ToString() + "," + this.gameVersion + "," + this.shortDesc.Escape() + "," + this.desc.Escape() + "\"";
```

Maybe we should make sure the header has the correct number of segents?

**Comment by mattr-** [comment]
I have more work in progress to limit what we accept but I wanted to get an initial version out. I'm happy to close this if you'd rather wait for the version that's more strict.

Where did you find the code for the blueprint header strings? I'm not super up to speed on any sort of game dev, so I've kinda been flying by the seat of my pants. 😄

**Comment by LRFalk01** [comment]
I'm fine with a plan to make it strict. I doubt anyone other than the DSB website uses this. I got the code from the decompiled game DLL. It's how I created this gem.

**Pull request merged**
